[package]
license = "MIT OR Apache-2.0"
name = "sage-core"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = { workspace = true }
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = { workspace = true }
sage-git = { path = "../sage-git" }
sage-graph = { path = "../sage-graph" }
sage-tui = { path = "../sage-tui" }
serde_json = "1.0.140"
uuid = "1.16.0"
openai-api-rs = "6.0.4"
indicatif = "0.18"
fuzzy-matcher = "0.3.7"
octocrab = { version = "0.44", default-features = false, features = ["rustls", "default-client"] }
sage-config = { path = "../sage-config" }
sage-events = { path = "../sage-events" }
console = "0.16"
thiserror.workspace = true
semver = { version = "1.0.26", features = ["serde"] }
dirs = "6.0.0"
reqwest = { version = "0.12.22", default-features = false, features = ["rustls-tls", "json"] }
tokio = "1.47"
terminal_size = "0.4.2"
openssl = { workspace = true }
