[package]
license = "MIT OR Apache-2.0"
name = "sage-core"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = { workspace = true }
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = { workspace = true }
sage-git = { path = "../sage-git" }
sage-graph = { path = "../sage-graph" }
sage-tui = { path = "../sage-tui" }
serde_json = "1.0.140"
uuid = "1.16.0"
openai-api-rs = "6.0.4"
indicatif = "0.17.8"
fuzzy-matcher = "0.3.7"
octocrab = "0.44"
sage-config = { path = "../sage-config" }
console = "0.15.11"
thiserror.workspace = true
