[package]
license = "MIT OR Apache-2.0"
name = "sage-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = { workspace = true }
sage-git = { path = "../sage-git" }
sage-utils = { path = "../sage-utils" }
serde_json = "1.0.140"
uuid = "1.16.0"
