[workspace]
members = ["bins/*", "crates/*"]
resolver = "3"

default-members = ["bins/sage-cli"]

# ───────────────────────────────────────
# Shared dependency versions
# Any workspace crate can now say `serde = { workspace = true }`
# and it will pull the exact version declared here.
[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = { version = "0.1", features = ["log"] }
colored = "3.0"
# ───────────────────────────────────────
# Compilation profiles
[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
