# Cargo configuration for fast development builds

[net]
git-fetch-with-cli = true

# Use multiple codegen units for faster compilation (trades compile time for runtime performance)
[profile.dev]
# Cranelift backend for faster debug builds (requires nightly)
# Uncomment if using nightly:
# codegen-backend = "cranelift"

# Faster compilation settings
codegen-units = 256
debug = 1  # Minimal debug info

[profile.dev.package."*"]
# Optimize dependencies even in debug mode
opt-level = 2

# Release build optimizations
[profile.release]
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"

# Special profile for CI/testing - fast to compile but with some optimizations
[profile.ci]
inherits = "dev"
opt-level = 1

# Profile for profiling/benchmarking
[profile.bench]
inherits = "release"
debug = true
