# Cargo configuration for cross-platform builds

[net]
git-fetch-with-cli = true

[build]
rustflags = ["-Z", "threads=8", "-C", "link-arg=-fuse-ld=lld"]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
