[package]
license = "MIT OR Apache-2.0"
name = "sage-git"
version = "0.1.0"
edition = "2024"

[dependencies]
hack-workspace = { version = "0.1", path = "../../hack-workspace" }
anyhow.workspace = true
gix = "0.73"
gix-worktree-state = "0.20"
chrono = "0.4"
