name: CalVer Release

on:
  push:
    branches:
      - fresh

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: calver-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  determine-version:
    name: Determine CalVer Version
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    outputs:
      version: ${{ steps.calver.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Compute CalVer version
        id: calver
        shell: bash
        run: |
          set -euo pipefail

          YEAR=$(date -u '+%Y')
          MONTH=$(date -u '+%-m')
          DAY=$(date -u '+%-d')

          DAY_VALUE=$((10#$DAY))
          MAX_RELEASE=0
          TAG_PREFIX="${YEAR}.${MONTH}."

          while IFS= read -r tag; do
            patch_part="${tag#${TAG_PREFIX}}"

            if [[ "$patch_part" != "$tag" && "$patch_part" =~ ^[0-9]+$ ]]; then
              patch_value=$((10#$patch_part))
              tag_day=$((patch_value / 1000))

              if (( tag_day == DAY_VALUE )); then
                release=$((patch_value % 1000))
                if (( release > MAX_RELEASE )); then
                  MAX_RELEASE=$release
                fi
              fi
            fi
          done < <(git tag -l "${TAG_PREFIX}*")

          NEXT_RELEASE=$((MAX_RELEASE + 1))
          # Encode the day and the intra-day release counter into the SemVer patch
          PATCH=$((DAY_VALUE * 1000 + NEXT_RELEASE))
          VERSION="${YEAR}.${MONTH}.${PATCH}"

          echo "Computed CalVer version: ${VERSION}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

  run-release-workflow:
    name: Trigger Release Workflow
    needs: determine-version
    if: needs.determine-version.outputs.version != ''
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.determine-version.outputs.version }}
    secrets: inherit
