name: Update Copyright Year

on:
  schedule:
    # Run at 00:05 on January 1st
    - cron: '5 0 1 1 *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-copyright:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper PR creation

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Get current year
        id: year
        run: |
          CURRENT_YEAR=$(date +%Y)
          echo "YEAR=$CURRENT_YEAR" >> $GITHUB_ENV
          echo "Current year is $CURRENT_YEAR"

      - name: Update license files
        id: update_licenses
        run: |
          # Initialize error tracking
          ERRORS=""
          
          # Update MIT license file
          if [ -f LICENSE-MIT ]; then
            # More robust pattern that handles various copyright formats
            if ! sed -i -E "s/Copyright ?\(c\) ?([0-9]{4}(-[0-9]{4})?) Sage contributors/Copyright (c) $YEAR Sage contributors/" LICENSE-MIT; then
              ERRORS="$ERRORS\n- Failed to update LICENSE-MIT"
            else
              echo "Updated copyright year in LICENSE-MIT"
              cat LICENSE-MIT | grep -E "Copyright.+Sage contributors" || echo "Warning: Could not verify copyright line in LICENSE-MIT"
            fi
          else
            ERRORS="$ERRORS\n- LICENSE-MIT file not found"
          fi
          
          # Update Apache license file
          if [ -f LICENSE-APACHE ]; then
            # More robust pattern that handles various copyright formats
            if ! sed -i -E "s/Copyright ?\(c\) ?([0-9]{4}(-[0-9]{4})?) Sage contributors/Copyright (c) $YEAR Sage contributors/" LICENSE-APACHE; then
              ERRORS="$ERRORS\n- Failed to update LICENSE-APACHE"
            else
              echo "Updated copyright year in LICENSE-APACHE"
              cat LICENSE-APACHE | grep -E "Copyright.+Sage contributors" || echo "Warning: Could not verify copyright line in LICENSE-APACHE"
            fi
          else
            ERRORS="$ERRORS\n- LICENSE-APACHE file not found"
          fi
          
          # Check for Cargo.toml files without license field
          MISSING_LICENSES=""
          while IFS= read -r file; do
            if ! grep -q 'license = "MIT OR Apache-2.0"' "$file"; then
              MISSING_LICENSES="$MISSING_LICENSES\n- $file"
            fi
          done < <(find . -name "Cargo.toml" -not -path "./target/*")
          
          if [ -n "$MISSING_LICENSES" ]; then
            ERRORS="$ERRORS\n- The following Cargo.toml files are missing license fields:$MISSING_LICENSES"
          fi
          
          # Save errors for creating issue if needed
          if [ -n "$ERRORS" ]; then
            {
              echo "ERRORS<<EOF"
              echo -e "$ERRORS"
              echo "EOF"
              echo "HAS_ERRORS=true"
            } >> $GITHUB_ENV
          fi

      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "No changes detected"
          else
            echo "CHANGES=true" >> $GITHUB_ENV
            echo "Files changed:"
            git diff --name-only
          fi

      - name: Create Pull Request
        if: env.CHANGES == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update copyright year to ${{ env.YEAR }}"
          title: "Update copyright year to ${{ env.YEAR }}"
          body: |
            This is an automated PR to update the copyright year to ${{ env.YEAR }}.
            
            The update was performed by the scheduled GitHub Action that runs at the beginning of each year.
          branch: update-copyright-year
          delete-branch: true
          base: main  # Explicitly specify the base branch

      - name: PR Result
        if: env.CHANGES == 'true'
        run: |
          echo "Pull Request URL: ${{ steps.create-pr.outputs.pull-request-url }}"
          echo "Pull Request Number: ${{ steps.create-pr.outputs.pull-request-number }}"

      - name: Create Issue for Errors
        if: env.HAS_ERRORS == 'true'
        uses: peter-evans/create-issue@v4
        with:
          title: "Failed to update copyright year to ${{ env.YEAR }}"
          body: |
            The scheduled GitHub Action to update the copyright year encountered the following issues:
            
            ${{ env.ERRORS }}
            
            Please manually address these issues.
          labels: bug, automation
